# Generated by Django 2.1.4 on 2018-12-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20181228_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file_type',
            field=models.CharField(max_length=15),
        ),
    ]
